package software.practice.distribution.entity;

public class ApplicationResponse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_response.application_response_id
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    private Integer applicationResponseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_response.application_response_ispass
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    private Byte applicationResponseIspass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_response.application_response_application
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    private Integer applicationResponseApplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_response.application_response_message
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    private String applicationResponseMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_response.application_response_id
     *
     * @return the value of application_response.application_response_id
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public Integer getApplicationResponseId() {
        return applicationResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_response.application_response_id
     *
     * @param applicationResponseId the value for application_response.application_response_id
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public void setApplicationResponseId(Integer applicationResponseId) {
        this.applicationResponseId = applicationResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_response.application_response_ispass
     *
     * @return the value of application_response.application_response_ispass
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public Byte getApplicationResponseIspass() {
        return applicationResponseIspass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_response.application_response_ispass
     *
     * @param applicationResponseIspass the value for application_response.application_response_ispass
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public void setApplicationResponseIspass(Byte applicationResponseIspass) {
        this.applicationResponseIspass = applicationResponseIspass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_response.application_response_application
     *
     * @return the value of application_response.application_response_application
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public Integer getApplicationResponseApplication() {
        return applicationResponseApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_response.application_response_application
     *
     * @param applicationResponseApplication the value for application_response.application_response_application
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public void setApplicationResponseApplication(Integer applicationResponseApplication) {
        this.applicationResponseApplication = applicationResponseApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_response.application_response_message
     *
     * @return the value of application_response.application_response_message
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public String getApplicationResponseMessage() {
        return applicationResponseMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_response.application_response_message
     *
     * @param applicationResponseMessage the value for application_response.application_response_message
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    public void setApplicationResponseMessage(String applicationResponseMessage) {
        this.applicationResponseMessage = applicationResponseMessage == null ? null : applicationResponseMessage.trim();
    }
}