package software.practice.distribution.entity;

public class Application {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private Integer applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_community
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private Integer applicationCommunity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_user
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private Integer applicationUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_id
     *
     * @return the value of application.application_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_id
     *
     * @param applicationId the value for application.application_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_community
     *
     * @return the value of application.application_community
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Integer getApplicationCommunity() {
        return applicationCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_community
     *
     * @param applicationCommunity the value for application.application_community
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setApplicationCommunity(Integer applicationCommunity) {
        this.applicationCommunity = applicationCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_user
     *
     * @return the value of application.application_user
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Integer getApplicationUser() {
        return applicationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_user
     *
     * @param applicationUser the value for application.application_user
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setApplicationUser(Integer applicationUser) {
        this.applicationUser = applicationUser;
    }
}