package software.practice.distribution.entity;

import java.util.Date;

public class Application {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_id
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    private Integer applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_time
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    private Date applicationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_content
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    private String applicationContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_user
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    private Integer applicationUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_isdone
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    private Byte applicationIsdone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_id
     *
     * @return the value of application.application_id
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_id
     *
     * @param applicationId the value for application.application_id
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_time
     *
     * @return the value of application.application_time
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public Date getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_time
     *
     * @param applicationTime the value for application.application_time
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public void setApplicationTime(Date applicationTime) {
        this.applicationTime = applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_content
     *
     * @return the value of application.application_content
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public String getApplicationContent() {
        return applicationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_content
     *
     * @param applicationContent the value for application.application_content
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public void setApplicationContent(String applicationContent) {
        this.applicationContent = applicationContent == null ? null : applicationContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_user
     *
     * @return the value of application.application_user
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public Integer getApplicationUser() {
        return applicationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_user
     *
     * @param applicationUser the value for application.application_user
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public void setApplicationUser(Integer applicationUser) {
        this.applicationUser = applicationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_isdone
     *
     * @return the value of application.application_isdone
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public Byte getApplicationIsdone() {
        return applicationIsdone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_isdone
     *
     * @param applicationIsdone the value for application.application_isdone
     *
     * @mbg.generated Tue Apr 14 16:33:29 CST 2020
     */
    public void setApplicationIsdone(Byte applicationIsdone) {
        this.applicationIsdone = applicationIsdone;
    }
}