package software.practice.distribution.entity;

import java.util.Date;

public class Application {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_id
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    private Integer applicationId;

    private User user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_community
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    private Integer applicationCommunity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_user
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    private Integer applicationUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_isPass
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    private Byte applicationIspass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_time
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    private Date applicationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_id
     *
     * @return the value of application.application_id
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public Integer getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_id
     *
     * @param applicationId the value for application.application_id
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_community
     *
     * @return the value of application.application_community
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public Integer getApplicationCommunity() {
        return applicationCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_community
     *
     * @param applicationCommunity the value for application.application_community
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public void setApplicationCommunity(Integer applicationCommunity) {
        this.applicationCommunity = applicationCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_user
     *
     * @return the value of application.application_user
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public Integer getApplicationUser() {
        return applicationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_user
     *
     * @param applicationUser the value for application.application_user
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public void setApplicationUser(Integer applicationUser) {
        this.applicationUser = applicationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_isPass
     *
     * @return the value of application.application_isPass
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public Byte getApplicationIspass() {
        return applicationIspass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_isPass
     *
     * @param applicationIspass the value for application.application_isPass
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public void setApplicationIspass(Byte applicationIspass) {
        this.applicationIspass = applicationIspass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.application_time
     *
     * @return the value of application.application_time
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public Date getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.application_time
     *
     * @param applicationTime the value for application.application_time
     *
     * @mbg.generated Sun Apr 19 12:25:18 CST 2020
     */
    public void setApplicationTime(Date applicationTime) {
        this.applicationTime = applicationTime;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}