package software.practice.distribution.entity;

import java.util.Date;

public class Arrangement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangement.arrangement_id
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    private Integer arrangementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangement.arrangement_time
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    private Date arrangementTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangement.arrangement_package
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    private Integer arrangementPackage;

    private Package packageEntity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangement.arrangement_location
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    private Integer arrangementLocation;

    private Location locationEntity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangement.arrangement_id
     *
     * @return the value of arrangement.arrangement_id
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public Integer getArrangementId() {
        return arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangement.arrangement_id
     *
     * @param arrangementId the value for arrangement.arrangement_id
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public void setArrangementId(Integer arrangementId) {
        this.arrangementId = arrangementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangement.arrangement_time
     *
     * @return the value of arrangement.arrangement_time
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public Date getArrangementTime() {
        return arrangementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangement.arrangement_time
     *
     * @param arrangementTime the value for arrangement.arrangement_time
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public void setArrangementTime(Date arrangementTime) {
        this.arrangementTime = arrangementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangement.arrangement_package
     *
     * @return the value of arrangement.arrangement_package
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public Integer getArrangementPackage() {
        return arrangementPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangement.arrangement_package
     *
     * @param arrangementPackage the value for arrangement.arrangement_package
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public void setArrangementPackage(Integer arrangementPackage) {
        this.arrangementPackage = arrangementPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangement.arrangement_location
     *
     * @return the value of arrangement.arrangement_location
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public Integer getArrangementLocation() {
        return arrangementLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangement.arrangement_location
     *
     * @param arrangementLocation the value for arrangement.arrangement_location
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public void setArrangementLocation(Integer arrangementLocation) {
        this.arrangementLocation = arrangementLocation;
    }


    public Package getPackageEntity() {
        return packageEntity;
    }

    public void setPackageEntity(Package packageEntity) {
        this.packageEntity = packageEntity;
    }


    public Location getLocationEntity() {
        return locationEntity;
    }

    public void setLocationEntity(Location locationEntity) {
        this.locationEntity = locationEntity;
    }
}