package software.practice.distribution.entity;

public class Community {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_id
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_name
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    private String communityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_password
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    private String communityPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_id
     *
     * @return the value of community.community_id
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_id
     *
     * @param communityId the value for community.community_id
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_name
     *
     * @return the value of community.community_name
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_name
     *
     * @param communityName the value for community.community_name
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_password
     *
     * @return the value of community.community_password
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    public String getCommunityPassword() {
        return communityPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_password
     *
     * @param communityPassword the value for community.community_password
     *
     * @mbg.generated Fri Apr 17 12:25:01 CST 2020
     */
    public void setCommunityPassword(String communityPassword) {
        this.communityPassword = communityPassword == null ? null : communityPassword.trim();
    }
}