package software.practice.distribution.entity;

import java.util.ArrayList;
import java.util.List;

public class DealExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public DealExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealIdIsNull() {
            addCriterion("deal_id is null");
            return (Criteria) this;
        }

        public Criteria andDealIdIsNotNull() {
            addCriterion("deal_id is not null");
            return (Criteria) this;
        }

        public Criteria andDealIdEqualTo(Integer value) {
            addCriterion("deal_id =", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotEqualTo(Integer value) {
            addCriterion("deal_id <>", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThan(Integer value) {
            addCriterion("deal_id >", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_id >=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThan(Integer value) {
            addCriterion("deal_id <", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThanOrEqualTo(Integer value) {
            addCriterion("deal_id <=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdIn(List<Integer> values) {
            addCriterion("deal_id in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotIn(List<Integer> values) {
            addCriterion("deal_id not in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdBetween(Integer value1, Integer value2) {
            addCriterion("deal_id between", value1, value2, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_id not between", value1, value2, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealPackageIsNull() {
            addCriterion("deal_package is null");
            return (Criteria) this;
        }

        public Criteria andDealPackageIsNotNull() {
            addCriterion("deal_package is not null");
            return (Criteria) this;
        }

        public Criteria andDealPackageEqualTo(Integer value) {
            addCriterion("deal_package =", value, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageNotEqualTo(Integer value) {
            addCriterion("deal_package <>", value, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageGreaterThan(Integer value) {
            addCriterion("deal_package >", value, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_package >=", value, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageLessThan(Integer value) {
            addCriterion("deal_package <", value, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageLessThanOrEqualTo(Integer value) {
            addCriterion("deal_package <=", value, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageIn(List<Integer> values) {
            addCriterion("deal_package in", values, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageNotIn(List<Integer> values) {
            addCriterion("deal_package not in", values, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageBetween(Integer value1, Integer value2) {
            addCriterion("deal_package between", value1, value2, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealPackageNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_package not between", value1, value2, "dealPackage");
            return (Criteria) this;
        }

        public Criteria andDealContentIsNull() {
            addCriterion("deal_content is null");
            return (Criteria) this;
        }

        public Criteria andDealContentIsNotNull() {
            addCriterion("deal_content is not null");
            return (Criteria) this;
        }

        public Criteria andDealContentEqualTo(String value) {
            addCriterion("deal_content =", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentNotEqualTo(String value) {
            addCriterion("deal_content <>", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentGreaterThan(String value) {
            addCriterion("deal_content >", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentGreaterThanOrEqualTo(String value) {
            addCriterion("deal_content >=", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentLessThan(String value) {
            addCriterion("deal_content <", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentLessThanOrEqualTo(String value) {
            addCriterion("deal_content <=", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentLike(String value) {
            addCriterion("deal_content like", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentNotLike(String value) {
            addCriterion("deal_content not like", value, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentIn(List<String> values) {
            addCriterion("deal_content in", values, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentNotIn(List<String> values) {
            addCriterion("deal_content not in", values, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentBetween(String value1, String value2) {
            addCriterion("deal_content between", value1, value2, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealContentNotBetween(String value1, String value2) {
            addCriterion("deal_content not between", value1, value2, "dealContent");
            return (Criteria) this;
        }

        public Criteria andDealIspassIsNull() {
            addCriterion("deal_isPass is null");
            return (Criteria) this;
        }

        public Criteria andDealIspassIsNotNull() {
            addCriterion("deal_isPass is not null");
            return (Criteria) this;
        }

        public Criteria andDealIspassEqualTo(Byte value) {
            addCriterion("deal_isPass =", value, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassNotEqualTo(Byte value) {
            addCriterion("deal_isPass <>", value, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassGreaterThan(Byte value) {
            addCriterion("deal_isPass >", value, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassGreaterThanOrEqualTo(Byte value) {
            addCriterion("deal_isPass >=", value, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassLessThan(Byte value) {
            addCriterion("deal_isPass <", value, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassLessThanOrEqualTo(Byte value) {
            addCriterion("deal_isPass <=", value, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassIn(List<Byte> values) {
            addCriterion("deal_isPass in", values, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassNotIn(List<Byte> values) {
            addCriterion("deal_isPass not in", values, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassBetween(Byte value1, Byte value2) {
            addCriterion("deal_isPass between", value1, value2, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealIspassNotBetween(Byte value1, Byte value2) {
            addCriterion("deal_isPass not between", value1, value2, "dealIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIsNull() {
            addCriterion("deal_response is null");
            return (Criteria) this;
        }

        public Criteria andDealResponseIsNotNull() {
            addCriterion("deal_response is not null");
            return (Criteria) this;
        }

        public Criteria andDealResponseEqualTo(String value) {
            addCriterion("deal_response =", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseNotEqualTo(String value) {
            addCriterion("deal_response <>", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseGreaterThan(String value) {
            addCriterion("deal_response >", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseGreaterThanOrEqualTo(String value) {
            addCriterion("deal_response >=", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseLessThan(String value) {
            addCriterion("deal_response <", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseLessThanOrEqualTo(String value) {
            addCriterion("deal_response <=", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseLike(String value) {
            addCriterion("deal_response like", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseNotLike(String value) {
            addCriterion("deal_response not like", value, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseIn(List<String> values) {
            addCriterion("deal_response in", values, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseNotIn(List<String> values) {
            addCriterion("deal_response not in", values, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseBetween(String value1, String value2) {
            addCriterion("deal_response between", value1, value2, "dealResponse");
            return (Criteria) this;
        }

        public Criteria andDealResponseNotBetween(String value1, String value2) {
            addCriterion("deal_response not between", value1, value2, "dealResponse");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 17 13:03:48 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal
     *
     * @mbg.generated Fri Apr 17 13:03:48 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}