package software.practice.distribution.entity;

import java.util.ArrayList;
import java.util.List;

public class DealResponseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public DealResponseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealResponseIdIsNull() {
            addCriterion("deal_response_id is null");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdIsNotNull() {
            addCriterion("deal_response_id is not null");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdEqualTo(Integer value) {
            addCriterion("deal_response_id =", value, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdNotEqualTo(Integer value) {
            addCriterion("deal_response_id <>", value, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdGreaterThan(Integer value) {
            addCriterion("deal_response_id >", value, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_response_id >=", value, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdLessThan(Integer value) {
            addCriterion("deal_response_id <", value, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdLessThanOrEqualTo(Integer value) {
            addCriterion("deal_response_id <=", value, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdIn(List<Integer> values) {
            addCriterion("deal_response_id in", values, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdNotIn(List<Integer> values) {
            addCriterion("deal_response_id not in", values, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdBetween(Integer value1, Integer value2) {
            addCriterion("deal_response_id between", value1, value2, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_response_id not between", value1, value2, "dealResponseId");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassIsNull() {
            addCriterion("deal_response_ispass is null");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassIsNotNull() {
            addCriterion("deal_response_ispass is not null");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassEqualTo(Byte value) {
            addCriterion("deal_response_ispass =", value, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassNotEqualTo(Byte value) {
            addCriterion("deal_response_ispass <>", value, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassGreaterThan(Byte value) {
            addCriterion("deal_response_ispass >", value, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassGreaterThanOrEqualTo(Byte value) {
            addCriterion("deal_response_ispass >=", value, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassLessThan(Byte value) {
            addCriterion("deal_response_ispass <", value, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassLessThanOrEqualTo(Byte value) {
            addCriterion("deal_response_ispass <=", value, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassIn(List<Byte> values) {
            addCriterion("deal_response_ispass in", values, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassNotIn(List<Byte> values) {
            addCriterion("deal_response_ispass not in", values, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassBetween(Byte value1, Byte value2) {
            addCriterion("deal_response_ispass between", value1, value2, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseIspassNotBetween(Byte value1, Byte value2) {
            addCriterion("deal_response_ispass not between", value1, value2, "dealResponseIspass");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageIsNull() {
            addCriterion("deal_response_message is null");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageIsNotNull() {
            addCriterion("deal_response_message is not null");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageEqualTo(String value) {
            addCriterion("deal_response_message =", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageNotEqualTo(String value) {
            addCriterion("deal_response_message <>", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageGreaterThan(String value) {
            addCriterion("deal_response_message >", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageGreaterThanOrEqualTo(String value) {
            addCriterion("deal_response_message >=", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageLessThan(String value) {
            addCriterion("deal_response_message <", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageLessThanOrEqualTo(String value) {
            addCriterion("deal_response_message <=", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageLike(String value) {
            addCriterion("deal_response_message like", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageNotLike(String value) {
            addCriterion("deal_response_message not like", value, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageIn(List<String> values) {
            addCriterion("deal_response_message in", values, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageNotIn(List<String> values) {
            addCriterion("deal_response_message not in", values, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageBetween(String value1, String value2) {
            addCriterion("deal_response_message between", value1, value2, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseMessageNotBetween(String value1, String value2) {
            addCriterion("deal_response_message not between", value1, value2, "dealResponseMessage");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealIsNull() {
            addCriterion("deal_response_deal is null");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealIsNotNull() {
            addCriterion("deal_response_deal is not null");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealEqualTo(Integer value) {
            addCriterion("deal_response_deal =", value, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealNotEqualTo(Integer value) {
            addCriterion("deal_response_deal <>", value, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealGreaterThan(Integer value) {
            addCriterion("deal_response_deal >", value, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_response_deal >=", value, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealLessThan(Integer value) {
            addCriterion("deal_response_deal <", value, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealLessThanOrEqualTo(Integer value) {
            addCriterion("deal_response_deal <=", value, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealIn(List<Integer> values) {
            addCriterion("deal_response_deal in", values, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealNotIn(List<Integer> values) {
            addCriterion("deal_response_deal not in", values, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealBetween(Integer value1, Integer value2) {
            addCriterion("deal_response_deal between", value1, value2, "dealResponseDeal");
            return (Criteria) this;
        }

        public Criteria andDealResponseDealNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_response_deal not between", value1, value2, "dealResponseDeal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal_response
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 15 18:11:16 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}