package software.practice.distribution.entity;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location_id
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location_name
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location_community
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    private Integer locationCommunity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_id
     *
     * @return the value of location.location_id
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_id
     *
     * @param locationId the value for location.location_id
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_name
     *
     * @return the value of location.location_name
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_name
     *
     * @param locationName the value for location.location_name
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName == null ? null : locationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_community
     *
     * @return the value of location.location_community
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public Integer getLocationCommunity() {
        return locationCommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_community
     *
     * @param locationCommunity the value for location.location_community
     *
     * @mbg.generated Fri Apr 24 16:31:47 CST 2020
     */
    public void setLocationCommunity(Integer locationCommunity) {
        this.locationCommunity = locationCommunity;
    }
}