package software.practice.distribution.entity;

import java.util.Date;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private Integer notificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_time
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private Date notificationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_content
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private String notificationContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_id
     *
     * @return the value of notification.notification_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Integer getNotificationId() {
        return notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_id
     *
     * @param notificationId the value for notification.notification_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_time
     *
     * @return the value of notification.notification_time
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Date getNotificationTime() {
        return notificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_time
     *
     * @param notificationTime the value for notification.notification_time
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setNotificationTime(Date notificationTime) {
        this.notificationTime = notificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_content
     *
     * @return the value of notification.notification_content
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public String getNotificationContent() {
        return notificationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_content
     *
     * @param notificationContent the value for notification.notification_content
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setNotificationContent(String notificationContent) {
        this.notificationContent = notificationContent == null ? null : notificationContent.trim();
    }
}