package software.practice.distribution.entity;

public class Property {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property_name
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private String propertyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column property.property_password
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    private String propertyPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property_id
     *
     * @return the value of property.property_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property_id
     *
     * @param propertyId the value for property.property_id
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property_name
     *
     * @return the value of property.property_name
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property_name
     *
     * @param propertyName the value for property.property_name
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column property.property_password
     *
     * @return the value of property.property_password
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public String getPropertyPassword() {
        return propertyPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column property.property_password
     *
     * @param propertyPassword the value for property.property_password
     *
     * @mbg.generated Wed Apr 15 18:11:16 CST 2020
     */
    public void setPropertyPassword(String propertyPassword) {
        this.propertyPassword = propertyPassword == null ? null : propertyPassword.trim();
    }
}