package software.practice.distribution.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
import software.practice.distribution.entity.ApplicationResponse;
import software.practice.distribution.entity.ApplicationResponseExample;

import java.util.List;

@Repository
public interface ApplicationResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    long countByExample(ApplicationResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int deleteByExample(ApplicationResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int deleteByPrimaryKey(Integer applicationResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int insert(ApplicationResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int insertSelective(ApplicationResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    List<ApplicationResponse> selectByExampleWithRowbounds(ApplicationResponseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    List<ApplicationResponse> selectByExample(ApplicationResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    ApplicationResponse selectByPrimaryKey(Integer applicationResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") ApplicationResponse record, @Param("example") ApplicationResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int updateByExample(@Param("record") ApplicationResponse record, @Param("example") ApplicationResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int updateByPrimaryKeySelective(ApplicationResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application_response
     *
     * @mbg.generated Thu Apr 16 15:44:10 CST 2020
     */
    int updateByPrimaryKey(ApplicationResponse record);
}