package software.practice.distribution.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import software.practice.distribution.entity.DealResponse;
import software.practice.distribution.entity.DealResponseExample;

public interface DealResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    long countByExample(DealResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int deleteByExample(DealResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int deleteByPrimaryKey(Integer dealResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int insert(DealResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int insertSelective(DealResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    List<DealResponse> selectByExample(DealResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    DealResponse selectByPrimaryKey(Integer dealResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") DealResponse record, @Param("example") DealResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int updateByExample(@Param("record") DealResponse record, @Param("example") DealResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int updateByPrimaryKeySelective(DealResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal_response
     *
     * @mbg.generated Wed Apr 15 11:06:09 CST 2020
     */
    int updateByPrimaryKey(DealResponse record);
}