server:
  port: 8443
  ssl:
    key-store: classpath:www.liyiersan.club.jks
    key-store-password: efdpvi3k05s11
    key-store-type: JKS


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    property-naming-strategy: LOWER_CAMEL_CASE
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://121.199.47.228:3306/material_distribution?useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #开启上传功能
      enabled: true
      #文件写入磁盘的阈值
      file-size-threshold : 2KB
      # 最大文件大小
      max-file-size : 20MB
      # 最大请求大小
      max-request-size : 20MB

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: software.practice.distribution.entity